[project]
name = "onnx-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.3",
    "onnxruntime>=1.23.2",
    "transformers>=4.57.1",
    "uvicorn>=0.38.0",
]
